In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from google.colab import files
import io

data=files.upload()


Saving area-ml.csv to area-ml.csv


In [ ]:
df=pd.read_csv(io.StringIO(data['area-ml.csv'].decode('utf-8')))
df

area  bedrooms  age   price
0  2200       3.0   20  270000
1  3300       4.0   15  330000
2  3700       NaN   18  540900
3  4400       3.0   30  680400
4  5500       5.0    8  775000

In [ ]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [ ]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2200       3.0   20  270000
1  3300       4.0   15  330000
2  3700       3.0   18  540900
3  4400       3.0   30  680400
4  5500       5.0    8  775000

In [ ]:
model=linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [ ]:
model.coef_

array([    213.92036879, -106476.18390524,   -2347.87886189])

In [ ]:
model.intercept_

128129.84857736231

In [ ]:
model.predict([[3100,3,20]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([424896.86286482])

In [ ]:
model.predict([[6000,3,25]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1033526.53803883])

In [ ]:
import pickle
with open('model_pickle','wb') as f:
  pickle.dump(model,f)